### ISSUE TITLE
How to hook this new PrincipalBuilder to an existing Kafka?

### ISSUE THREAD

**Issue by Benardi** [traiana/kafka-spiffe-principal#5]
How to hook this custom KafkaPrincipalBuilder to an existing Kafka?
Is it just a matter of compiling this project and adding the .jar to the libs directory in Kafka or are there other steps?

**Comment by abhinavdangi** [comment]
@Benardi, I am also searching for the same answer. It would be great if you could help me.

**Comment by Benardi** [comment]
> @Benardi, I am also searching for the same answer. It would be great if you could help me.

Hey, @abhinavdangi, I've written down the solution that worked for me in a [fork I've made](https://github.com/ufcg-lsd/kafka-spiffe-principal). 

I've ended up updating the environment variable CLASSPATH with the path to the .jar built via this repo and exporting CLASSPATH in the same terminal I raised the broker. For more info, you could check the [fork](https://github.com/ufcg-lsd/kafka-spiffe-principal). 

Also, feel free to comment or raise issues in the fork if you see something that I can improve.

**Comment by abhinavdangi** [comment]
@Benardi, I ran the steps according to your fork. I'm facing the following issue:
```
org.apache.kafka.common.config.ConfigException: Invalid value io.okro.kafka.SpiffePrincipalBuilder for configuration principal.builder.class: Class io.okro.kafka.SpiffePrincipalBuilder could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1386)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1389)
        at kafka.Kafka$.buildServer(Kafka.scala:67)
        at kafka.Kafka$.main(Kafka.scala:87)
```
When I run the Kafka server, I see that the classpath contains the path of kafka-spiffe-principal-2.0.0.jar.
I'm using Kafka 2.8.0

**Comment by royantman** [comment]
I no longer maintain this (not the repo owner/no longer in the org).
I am also certain you figured out the miss configuration.

But for anyone bumping into this:

```
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
principal.builder.class=io.okro.kafka.SpiffePrincipalBuilder
```
And jar should be available via *CLASSPATH* or by putting the jar in `${YOUR_KAFKA_INSTALLATION_DIR}/libs` 
True for version 2.6.1, never tested on a newer version.
